baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-blog-awesome'

[menu]
  [[menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Inicio'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Cartas virtuales'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'Sobre el sitio'
    url = '/Sobre el sitio/'
    weight = 30

[params.author]
  avatar = "me.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Rafa'Site"
  name = "Sidharth R"
  description = "Una plataforma diseñada únicamente para sacarte una sonrisa con cada clic"
